<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RTFTH45" failures="1" tests="4" name="UI_TestNG.ReportGenerationTestNg" time="1.695" errors="0" timestamp="2024-06-09T13:15:42 BST" skipped="0">
  <testcase classname="UI_TestNG.ReportGenerationTestNg" name="reporterTest1" time="1.690">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at UI_TestNG.ReportGenerationTestNg.reporterTest1(ReportGenerationTestNg.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Method name is - reporterTest1
This is test1
<a href="C:\Users\Engr. Abbey\eclipse-workspace\WebPortal_TestNg\screenshot">Test Results</a>]]>
    </system-out>
  </testcase> <!-- reporterTest1 -->
  <testcase classname="UI_TestNG.ReportGenerationTestNg" name="reporterTest2" time="0.002">
    <system-out>
      <![CDATA[Method name is - reporterTest2
Status of execution is - 1]]>
    </system-out>
  </testcase> <!-- reporterTest2 -->
  <testcase classname="UI_TestNG.ReportGenerationTestNg" name="reporterTest4" time="0.001">
    <system-out>
      <![CDATA[Method name is - reporterTest4
Status of execution is - 1]]>
    </system-out>
  </testcase> <!-- reporterTest4 -->
  <testcase classname="UI_TestNG.ReportGenerationTestNg" name="reporterTest3" time="0.002">
    <system-out>
      <![CDATA[Method name is - reporterTest3
Status of execution is - 1]]>
    </system-out>
  </testcase> <!-- reporterTest3 -->
  <system-out>
    <![CDATA[Method name is - reporterTest1
This is test1
<a href="C:\Users\Engr. Abbey\eclipse-workspace\WebPortal_TestNg\screenshot">Test Results</a>
Method name is - reporterTest2
Status of execution is - 1
Method name is - reporterTest3
Status of execution is - 1
Method name is - reporterTest4
Status of execution is - 1]]>
  </system-out>
</testsuite> <!-- UI_TestNG.ReportGenerationTestNg -->
